# Site settings
title: crgk
description: >
    Blog and stuff by Chad Knight.
baseurl: "" 
url: "http://crgk.github.io" # the base hostname & protocol for your site
author: 
  name: Chad Knight
  email: chadrknight@gmail.com
  twitter: crgk_6
  github:  crgk

defaults:
  - 
    scope:
      path: ""
    values:
      author: "Chad Knight"
      theme_color: "#306090"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "til"
      type: "posts"
    values:
      layout: "post"
      category: til

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
