# Site settings
title: Chadthoughts
description: >
    Basically www.chadhoughts.gov.www\chadthoughts
baseurl: "" 
url: "http://crgk.github.io" # the base hostname & protocol for your site
author: 
  name: Chad Knight
  email: chadrknight@gmail.com
  twitter: crgk_6
  github:  crgk

# Build settings
markdown: kramdown
kramdown:
  input: GFM

gems:
    - jekyll-mentions
    - jemoji

